name: Release

on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Download dependencies
      run: go mod download

    - name: Build binaries
      run: |
        GOOS=linux GOARCH=amd64 make build && tar -czf kubediff-linux-amd64.tar.gz kubediff
        GOOS=linux GOARCH=arm64 make build && tar -czf kubediff-linux-arm64.tar.gz kubediff
        GOOS=darwin GOARCH=amd64 make build && tar -czf kubediff-darwin-amd64.tar.gz kubediff
        GOOS=darwin GOARCH=arm64 make build && tar -czf kubediff-darwin-arm64.tar.gz kubediff

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          kubediff-linux-amd64.tar.gz
          kubediff-linux-arm64.tar.gz
          kubediff-darwin-amd64.tar.gz
          kubediff-darwin-arm64.tar.gz
        generate_release_notes: true
